### ISSUE TITLE
notebook support

### ISSUE THREAD

**Issue by Konfekt** [wmvanvliet/jupyter-vim#9] opened 2018-11-07 12:44 UTC
When starting jupyter with the command `jupyter notebook` the file or range sent, for example by `JupyterRunFile` does not appear in the notebook.

From what I understand in https://github.com/ivanov/vim-ipython/issues/133#issuecomment-120449572 the supposed workflow is typing `% rerun` in the notebook for the sent range or file to appear. 

However, typing `:JupyterSendRange` in Vim and typing `% rerun` in the Jupyter notebook is not much more convenient than copying the range in Vim and pasting it into the Jupyter notebook. 

Therefore, I wonder why https://github.com/ivanov/vim-ipython/pull/150 did not receive any consideration in this (and other) fork of vim-ipython?

**Comment by Konfekt** [comment] 2018-12-06 12:08
In fact, I am an absolute beginner using Jupyter. But from what I understand reading the documentation and these issues, is that only `console` and `qtconsole` show the code sent from Vim, whereas in `notebook` typing `% rerun` is required. Is that it? Or does it work for `notebook` just as it does for `console` and `qtconsole`. In the latter two instances, it runs just fine over here.

**Comment by philipjhj** [comment] 2018-12-06 13:12
I did not test with the `notebook`  but in my jupyter `console` it does not show the code for me. If I use the %rerun magic as you describe then it is displayed. It is only the `qtconsole` that automatically lists the code for me.

I am using the native bash shell on Ubuntu 18.04.

**Comment by Konfekt** [comment] 2018-12-06 14:08
True, thank you, it is also broken in `console` over here. Then probably sending code to `console` is broken for similar reasons as it is for `notebook`.

**Comment by philipjhj** [comment] 2018-12-06 14:56
But it did work for you in the `console` at one point? If yes, any chance you would remember when?

**Comment by Konfekt** [comment] 2018-12-06 16:49
No, most probably not. I never really used Jupyter. I just thought it would because it should, as the documentation of this plug-in implies it.

**Comment by kimborgen** [comment] 2019-05-25 17:25
@philipjhj @Konfekt I figured it out for qtconsole (and ish for console). 
You need to set a configuration option for juptyter console and qtconsole manually. I did not find a similar option for notebook, but I did not explore further, maybe the configuration option for notebook has a different name?

Create configuration files
```
jupyter console --generate-config
jupyter qtconsole --generate-config
```
My config files was created in ~/.jupyter

Now you need to uncomment and change these config options to True

For qtconsole:
```
c.ConsoleWidget.include_other_output = True
```
For console:
```
c.ZMQTerminalInteractiveShell.include_other_output = True
```

Now code will be sent and executed as expected in qtconsole. Console will still not update but shows the result after you press enter.

@wmvanvliet This should be part of the README.

**Comment by wmvanvliet** [comment] 2019-05-25 20:09
> @wmvanvliet This should be part of the README.
done!

**Comment by bzinberg** [comment] 2019-05-27 07:30
@kimborgen I would be very surprised if there is an option to add remote inputs to the Jupyter notebook -- this would be a very involved UI project, as it's not clear that adding cells is always the right thing to do when a user executes code on the kernel (e.g. if it is a re-execution, scrap code, etc.).  That said, it sounds like [Jupytext](https://github.com/mwouts/jupytext) could be very useful for your situation.  I rarely view notebooks in the browser anymore -- I edit a code file in vim, use jupyter-vim to send lines to QtConsole when I want to execute, and Jupytext bidirectionally syncs the code file with an `.ipynb` which I can share with others who want that format.

**Comment by Konfekt** [comment] 2019-05-27 16:57
Dear @bzinberg , may I ask how jupytext syncs the code, as seemingly https://github.com/goerz/jupytext.vim/ converts it into a markdown, and not python file. But sending to `QtConsole` is only available, by this plug-in, in a python file type.

**Comment by bzinberg** [comment] 2019-05-27 17:32
@Konfect, looks like you and I linked to different plugins with similar names...

**Comment by bzinberg** [comment] 2019-05-27 17:35
@Konfekt Also, as of https://github.com/broesler/jupyter-vim/pull/2, sending to QtConsole works for Julia kernels too.

**Comment by Konfekt** [comment] 2019-05-27 19:07
Dear @bzinberg, When you say code file, you mean a python code file `notebook.py`, that is, and you installed a file watcher like `entr` or trigger by some event `jupytext --sync notebook.py`?

**Comment by bzinberg** [comment] 2019-05-27 19:47
The Jupyter kernel itself handles the updates via a ContentsManager -- see
the Jupytext documentation.  Personally I just develop `foo.py` in vim side
by side with a Jupyter QtConsole, and when I'm ready to share the notebook
I load `foo.ipynb` in the browser to preview (which auto-syncs via a hook
in the Jupyter kernel that recognizes the `.py` file has been modified more
recently than the `.ipynb`).

**Comment by wmvanvliet** [comment] 2019-06-25 12:49
From the point of view of this plugin, vim becomes one of many "clients" that are connected to the same jupyter kernel. The notebook is another client. You can open up some jupyter consoles and have them be clients. The issue is now how a jupyter notebook deals with input that is received from other clients. This is complicated from a UI perspective and something the notebook people should figure out. It is out of scope for the vim plugin.

Closing the issue for now.

**Closed by wmvanvliet** 2019-06-25 12:49 UTC
